AslanPageBundle_home:
    pattern:  /
    defaults: { _controller: AslanPageBundle:Page:home}  
#Multiki
AslanPageBundle_video:
    pattern:  /multiki
    defaults: { _controller: AslanPageBundle:Page:video}    
    
#Albums
AslanPageBundle_albums:
    pattern:  /fotografii
    defaults: { _controller: AslanPageBundle:Page:albums} 

AslanPageBundle_album:
    pattern:  /fotografii/{name}
    defaults: { _controller: AslanPageBundle:Page:album} 

#Afisha
AslanPageBundle_afisha:
    pattern:  /afisha
    defaults: { _controller: AslanPageBundle:Page:afisha}

AslanPageBundle_afisha_json:
    pattern:  /afisha_json
    defaults: { _controller: AslanPageBundle:Page:afishaJson}
    requirements:
        _method:  POST     

AslanPageBundle_afisha_slug:
    pattern:  /afisha/{slug}
    defaults: { _controller: AslanPageBundle:Page:afishaOne}

#Place
AslanPageBundle_place:
    pattern:  /mesta
    defaults: { _controller: AslanPageBundle:Page:place}
    
AslanPageBundle_place_slug:
    pattern:  /mesta/{slug}
    defaults: { _controller: AslanPageBundle:Page:placeOne}
    
#Categorii
AslanPageBundle_categorii:
    pattern:  /kategorii
    defaults: { _controller: AslanPageBundle:Page:categorii}

AslanPageBundle_page:
    pattern:  /{slug}
    defaults: { _controller: AslanPageBundle:Page:pageMenu}   
    
AslanPageBundle_photo:
    pattern:  /photo
    defaults: { _controller: AslanPageBundle:Page:photo}   

AslanPageBundle_life:
    pattern:  /life
    defaults: { _controller: AslanPageBundle:Page:life}   

AslanPageBundle_thirdmenu:
    pattern:  /thirdmenu
    defaults: { _controller: AslanPageBundle:Page:third}     

AslanPageBundle_blogs:
    pattern:  /blogs
    defaults: { _controller: AslanPageBundle:Page:blogs}

AslanPageBundle_blog:
    pattern:  /blog
    defaults: { _controller: AslanPageBundle:Page:blog}
    requirements:
        _method:  POST     
    
AslanPageBundle_video:
    pattern:  /movie
    defaults: { _controller: AslanPageBundle:Page:video } 
AslanPageBundle_video_preview:
    pattern:  /videoPreview
    defaults: { _controller: AslanPageBundle:Page:videoPreview } 		