parameters:
#    aslan_admin.example.class: Aslan\AdminBundle\Example

services:
#    aslan_admin.example:
#        class: %aslan_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
