parameters:
#    aslan_background.example.class: Aslan\BackgroundBundle\Example

services:
#    aslan_background.example:
#        class: %aslan_background.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
